---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.8.4.redhat-00002
    app.quarkus.io/build-timestamp: 2024-07-09 - 06:10:02 +0000
  labels:
    app.kubernetes.io/name: webhook-consumer-shipping
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: webhook-consumer-shipping
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http2
      port: 9080
      protocol: TCP
      targetPort: 9080
  selector:
    app.kubernetes.io/name: webhook-consumer-shipping
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.8.4.redhat-00002
    app.quarkus.io/build-timestamp: 2024-07-09 - 06:10:02 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: webhook-consumer-shipping
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: webhook-consumer-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-consumer-shipping
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.openshift.io/vcs-uri: <<unknown>>
        app.quarkus.io/quarkus-version: 3.8.4.redhat-00002
        app.quarkus.io/build-timestamp: 2024-07-09 - 06:10:02 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: webhook-consumer-shipping
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: macSecret
              value: "replace it"
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: quay.io/webhooksystem/webhook-consumer:V1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: webhook-consumer-shipping
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9080
              name: http2
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.8.4.redhat-00002
    app.quarkus.io/build-timestamp: 2024-07-09 - 06:10:02 +0000
  labels:
    app.kubernetes.io/name: webhook-consumer-shipping
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: webhook-consumer-shipping
spec:
  path: /
  port:
    targetPort: http2
  tls:
    insecureEdgeTerminationPolicy: None
    termination: edge
  to:
    kind: Service
    name: webhook-consumer-shipping
