kind: Secret
apiVersion: v1
metadata:
  name: order-created-event-openapi
  namespace: webhook-system-3scale
type: Opaque
stringData:
  orderCreatedEvent.yaml: |
    ---
      openapi: 3.0.3
      info:
        title: Order Created Event Callback
        version: 1.0.0
      paths:
         
            "/":
              post:
                requestBody:
                  description: order payload
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          orderId:
                            type: string
                            description: Unique identifier for the order
                          name:
                            type: string
                            description: Name of the person placing the order
                          email:
                            type: string
                            format: email
                            description: Email address of the person placing the order
                          status:
                            type: string
                            description: Current status of the order
                            enum:
                            - ORDER_CREATED
                            - ORDER_CONFIRMED
                            - ORDER_SHIPPED
                            - ORDER_DELIVERED
                            - ORDER_CANCELLED
                          accountId:
                            type: string
                            description: Account identifier associated with the order
                          createdAt:
                            type: integer
                            description: The timestamp when the order was created
                        required:
                        - orderId
                        - name
                        - email
                        - status
                        - accountId
                        - createdAt
                        additionalProperties: false
                responses:
                  '202':
                    description: Your server implementation should return this HTTP status
                      code if the data was received successfully
                security:
                - HmacAuth: []
      components:
        securitySchemes:
          HmacAuth:
            type: apiKey
            in: header
            name: X-HMAC-SIGNATURE
            description: HMAC authentication using the SHA-256 hash algorithm. The HMAC
              signature should be computed using the SHA-256 algorithm on a string concatenated
              from the method, path, body, and a secret key, and passed in the 'X-HMAC-SIGNATURE'
              header.
      security:
      - HmacAuth: []
