---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.8.4.redhat-00002
    app.quarkus.io/build-timestamp: 2024-07-09 - 05:59:19 +0000
  labels:
    app.kubernetes.io/name: webhook-dispatcher
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: webhook-dispatcher
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: webhook-dispatcher
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.8.4.redhat-00002
    app.quarkus.io/build-timestamp: 2024-07-09 - 05:59:19 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: webhook-dispatcher
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: webhook-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-dispatcher
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.openshift.io/vcs-uri: <<unknown>>
        app.quarkus.io/quarkus-version: 3.8.4.redhat-00002
        app.quarkus.io/build-timestamp: 2024-07-09 - 05:59:19 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: webhook-dispatcher
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: SMALLRYE_CONFIG_LOCATIONS
              value: /mnt/app-secret
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: quay.io/webhooksystem/webhook-dispatcher:V1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: webhook-dispatcher
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /mnt/app-secret
              name: app-secret
              readOnly: false
      volumes:
        - name: app-secret
          secret:
            optional: false
            secretName: webhook-dispatcher
