apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "amq-broker-operatorgroup"
  namespace: "webhook-system-amq-broker"
spec:
  targetNamespaces:
    - "webhook-system-amq-broker"