apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  application: broker-app
  name: broker
  namespace: webhook-system-amq-broker
spec:

  acceptors:
    - name: artemis-acceptor
      protocols: 'artemis,core,openwire'
      port: 61616
      sslEnabled: false
    - name: amqp-acceptor
      protocols: amqp
      port: 5672
      sslEnabled: false
  connectors:
    - port: 22222
      verifyHost: true
      wantClientAuth: true
      expose: true
      host: localhost
      needClientAuth: true
      name: connector0
      sslEnabled: false
      sniHost: localhost
      enabledProtocols: 'TLSv1,TLSv1.1,TLSv1.2'
      sslProvider: JDK
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 512Mi
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
    storage:
      size: 4Gi
  upgrades:
    enabled: false
    minor: false
