apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: 3scale-consumer-applications-cache
  namespace: webhook-system-data-grid
spec:
  clusterName: my-infinispan
  name: 3scale-consumer-applications-cache
  template: <replicated-cache mode="SYNC" statistics="true"><encoding media-type="application/x-protostream"/><expiration lifespan="300000" max-idle="-1"/><memory max-count="1000000" when-full="REMOVE"/><persistence passivation="false"><file-store/></persistence></replicated-cache>