apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-storage
  namespace: webhook-system-3scale
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi