apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: webhook-system-kafka
spec:
  entityOperator:
    tlsSidecar: {}
    topicOperator:
      reconciliationIntervalSeconds: 60
    userOperator:
      reconciliationIntervalSeconds: 60
  kafka:
 
    config:
      auto.create.topics.enable: false
      default.replication.factor: 3
      log.cleaner.delete.retention.ms: 3600000
      log.cleaner.enable: true
      log.cleanup.policy: delete
      log.retention.hours: 24
      message.max.bytes: 52428800
      min.insync.replicas: 2
      num.partitions: 1
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    
    - name: tls
      port: 9093
      tls: true
      type: internal
    
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    replicas: 3
    storage:
      type: jbod
      volumes:
      - deleteClaim: true
        id: 0
        size: 10Gi
        type: persistent-claim
      - deleteClaim: true
        id: 1
        size: 10Gi
        type: persistent-claim
    version: 3.7.0
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    replicas: 3
    storage:
      deleteClaim: true
      size: 5Gi
      type: persistent-claim